name: Deploy
on:
  schedule:
   - cron: '0 12 * * FRI'  # Every Fridat at midnight
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy webiste
        run: Makefile
