name: Deploy
on:
  schedule:
   - cron: '0 12 * * FRI'  # Every Fridat at midnight
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy webiste
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: Makefile
